---
language: python
services: docker

env:
  global:
    - ROLE_NAME: theo-agent
  matrix:
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: ubuntu1404
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: fedora27

install:
  - pip install testinfra==3.0.5 molecule[docker]==2.20.2

before_script:
  - cd ..
  - mv ansible-role-$ROLE_NAME ansible-$ROLE_NAME
  - cd ansible-$ROLE_NAME

script:
  - molecule --debug test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
