---
language: python
services: docker

env:
  global:
    - ROLE_NAME: theo-agent
  matrix:
    - MOLECULE_DISTRO=centos7
    - MOLECULE_DISTRO=centos8
    - MOLECULE_DISTRO=debian9
    - MOLECULE_DISTRO=debian10
    - MOLECULE_DISTRO=ubuntu1404 REGISTRY_USER=theoapp
    - MOLECULE_DISTRO=ubuntu1604
    - MOLECULE_DISTRO=ubuntu1804
    - MOLECULE_DISTRO=ubuntu2004
    - MOLECULE_DISTRO=fedora31
    - MOLECULE_DISTRO=fedora32

install:
  - pip install ansible ansible-lint molecule[docker] testinfra yamllint

before_script:
  - cd ..
  - mv ansible-role-$ROLE_NAME ansible-$ROLE_NAME
  - cd ansible-$ROLE_NAME

script:
  - molecule --debug test --all

notifications:
  webhooks:
    urls: https://galaxy.ansible.com/api/v1/notifications/
    if: tag IS present
